name: team_project
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.0
  http: ^1.2.1
  shared_preferences: ^2.1.0
  retry: ^3.1.0
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.3
  firebase_database: ^10.1.0
  image_picker: ^1.1.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  intl: ^0.19.0
  provider: ^6.0.5
  fluttertoast: ^8.2.6
  mockito: ^5.4.4
  flutter_gemini: ^2.0.4
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.0.2
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/intl_en.json
    - lib/l10n/intl_ru.json
    - lib/images/default_photo.jpg